export default function RenderingList_2() {
  const products = [
    { id: 1, name: "Laptop" },
    { id: 2, name: "Mobile" },
    { id: 3, name: "Tablet" },
    { id: 4, name: "Camera" },
    { id: 5, name: "Headphone" },
    { id: 6, name: "Earphone" },
    { id: 7, name: "Watch" },
    { id: 8, name: "Shoes" },
    { id: 9, name: "T-Shirt" },
    { id: 10, name: "Pant" },
    { id: 11, name: "Laptop" },
  ];
  const product = products.map((product) => <h3 key={product.id}>{product.name}</h3>);
  return (
    <div>
      <h3>
        In this method the error is removed which was generated by adding the
        same element.
      </h3>
      {product}
      <h3>Now you can see that the error is removed.</h3>
    </div>
  );
}
